### ISSUE TITLE
Non-US version AR Code Support

### ISSUE THREAD

**Issue by Zanto018** [RenegadeRaven/CuteCharmIDGenie#4]
**If not, describe why and how the requested feature will improve the project:**
The Calculator/Progr. converts your wishes into AR codes for the US Version of the Games an no DE version.

**Describe the solution you'd like:**
I dont know if this is posible to implement easyly but i wish for a way to convert into AR Codes for DE version.
In my case i only need it for Heart Gold but i dont know if this even lessens the scope of work...
Language of menu doesnt even matter... English is best i think.

**Comment by RenegadeRaven** [comment]
Just to confirm, you mean the german (**DE**utsch) version of the game, right?

**Comment by RenegadeRaven** [comment]
From what I've found, you can take a code made for US version and change one character to make it work for DE version.
Take it and change `B2111880 00000000` to `B2111860 00000000` (change the last 8 to a 6)

**Comment by RenegadeRaven** [comment]
Or you can use this version I quickly threw together for you. **WARNING: it's quite buggy,** but can work for now (if you really need a DE AR code asap)
[CuteCharmIDGenie alpha-dev(2023-11-24).zip](https://github.com/RenegadeRaven/CuteCharmIDGenie/files/13462073/CuteCharmIDGenie.alpha-dev.2023-11-24.zip)

I will be refining the added DE support, as well as looking into adding support for other versions, in a future release.

**Comment by RenegadeRaven** [comment]
New more stable version with complete DE version support: [CuteCharmIDGenie alpha-dev(2023-12-20).zip](https://github.com/RenegadeRaven/CuteCharmIDGenie/files/13724035/CuteCharmIDGenie.alpha-dev.2023-12-20.zip)
  
  
**Known Issue:**
 - settings.xml at *%LocalAppData%/RenegadeRaven/CuteCharmIDGenie* will need to be deleted before first run

**Comment by RenegadeRaven** [comment]
All officially translated versions have been added.

**Comment by RenegadeRaven** [comment]
Feature available in [version 1.2.0+](https://github.com/RenegadeRaven/CuteCharmIDGenie/releases/latest)
